# Generated by Django 4.1.6 on 2023-03-31 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task_category_task_deadline_task_status'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to='deadline',
        ),
    ]
